name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Adjust to the Node.js version you're using

    - name: Install dependencies
      run: |
        cd api_tests/
        npm install

    - name: Check Jest installation
      run: |
        cd api_tests/

    - name: Run tests with Jest
      run: |
        cd api_tests/
        npx jest
